package com.cursoliferay.liferay.portlets.alineaciones.model.impl;

import com.cursoliferay.liferay.portlets.alineaciones.model.Jugador;
import com.cursoliferay.liferay.portlets.alineaciones.model.JugadorModel;
import com.cursoliferay.liferay.portlets.alineaciones.model.JugadorSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Jugador service. Represents a row in the &quot;alineaciones_Jugador&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cursoliferay.liferay.portlets.alineaciones.model.JugadorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JugadorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JugadorImpl
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.Jugador
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.JugadorModel
 * @generated
 */
@JSON(strict = true)
public class JugadorModelImpl extends BaseModelImpl<Jugador>
    implements JugadorModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a jugador model instance should use the {@link com.cursoliferay.liferay.portlets.alineaciones.model.Jugador} interface instead.
     */
    public static final String TABLE_NAME = "alineaciones_Jugador";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "jugadorId", Types.BIGINT },
            { "partidoId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "nombre", Types.VARCHAR },
            { "dni", Types.VARCHAR },
            { "titular", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table alineaciones_Jugador (uuid_ VARCHAR(75) null,jugadorId LONG not null primary key,partidoId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nombre VARCHAR(75) null,dni VARCHAR(75) null,titular BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table alineaciones_Jugador";
    public static final String ORDER_BY_JPQL = " ORDER BY jugador.nombre ASC";
    public static final String ORDER_BY_SQL = " ORDER BY alineaciones_Jugador.nombre ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Jugador"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Jugador"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Jugador"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long PARTIDOID_COLUMN_BITMASK = 4L;
    public static long UUID_COLUMN_BITMASK = 8L;
    public static long NOMBRE_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.cursoliferay.liferay.portlets.alineaciones.model.Jugador"));
    private static ClassLoader _classLoader = Jugador.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Jugador.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _jugadorId;
    private long _partidoId;
    private long _originalPartidoId;
    private boolean _setOriginalPartidoId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _nombre;
    private String _dni;
    private boolean _titular;
    private long _columnBitmask;
    private Jugador _escapedModel;

    public JugadorModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Jugador toModel(JugadorSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Jugador model = new JugadorImpl();

        model.setUuid(soapModel.getUuid());
        model.setJugadorId(soapModel.getJugadorId());
        model.setPartidoId(soapModel.getPartidoId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setNombre(soapModel.getNombre());
        model.setDni(soapModel.getDni());
        model.setTitular(soapModel.getTitular());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Jugador> toModels(JugadorSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Jugador> models = new ArrayList<Jugador>(soapModels.length);

        for (JugadorSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _jugadorId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setJugadorId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _jugadorId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Jugador.class;
    }

    @Override
    public String getModelClassName() {
        return Jugador.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("jugadorId", getJugadorId());
        attributes.put("partidoId", getPartidoId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("nombre", getNombre());
        attributes.put("dni", getDni());
        attributes.put("titular", getTitular());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long jugadorId = (Long) attributes.get("jugadorId");

        if (jugadorId != null) {
            setJugadorId(jugadorId);
        }

        Long partidoId = (Long) attributes.get("partidoId");

        if (partidoId != null) {
            setPartidoId(partidoId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String nombre = (String) attributes.get("nombre");

        if (nombre != null) {
            setNombre(nombre);
        }

        String dni = (String) attributes.get("dni");

        if (dni != null) {
            setDni(dni);
        }

        Boolean titular = (Boolean) attributes.get("titular");

        if (titular != null) {
            setTitular(titular);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getJugadorId() {
        return _jugadorId;
    }

    @Override
    public void setJugadorId(long jugadorId) {
        _jugadorId = jugadorId;
    }

    @JSON
    @Override
    public long getPartidoId() {
        return _partidoId;
    }

    @Override
    public void setPartidoId(long partidoId) {
        _columnBitmask |= PARTIDOID_COLUMN_BITMASK;

        if (!_setOriginalPartidoId) {
            _setOriginalPartidoId = true;

            _originalPartidoId = _partidoId;
        }

        _partidoId = partidoId;
    }

    public long getOriginalPartidoId() {
        return _originalPartidoId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getNombre() {
        if (_nombre == null) {
            return StringPool.BLANK;
        } else {
            return _nombre;
        }
    }

    @Override
    public void setNombre(String nombre) {
        _columnBitmask = -1L;

        _nombre = nombre;
    }

    @JSON
    @Override
    public String getDni() {
        if (_dni == null) {
            return StringPool.BLANK;
        } else {
            return _dni;
        }
    }

    @Override
    public void setDni(String dni) {
        _dni = dni;
    }

    @JSON
    @Override
    public boolean getTitular() {
        return _titular;
    }

    @Override
    public boolean isTitular() {
        return _titular;
    }

    @Override
    public void setTitular(boolean titular) {
        _titular = titular;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Jugador.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Jugador.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Jugador toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Jugador) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        JugadorImpl jugadorImpl = new JugadorImpl();

        jugadorImpl.setUuid(getUuid());
        jugadorImpl.setJugadorId(getJugadorId());
        jugadorImpl.setPartidoId(getPartidoId());
        jugadorImpl.setGroupId(getGroupId());
        jugadorImpl.setCompanyId(getCompanyId());
        jugadorImpl.setUserId(getUserId());
        jugadorImpl.setUserName(getUserName());
        jugadorImpl.setCreateDate(getCreateDate());
        jugadorImpl.setModifiedDate(getModifiedDate());
        jugadorImpl.setNombre(getNombre());
        jugadorImpl.setDni(getDni());
        jugadorImpl.setTitular(getTitular());

        jugadorImpl.resetOriginalValues();

        return jugadorImpl;
    }

    @Override
    public int compareTo(Jugador jugador) {
        int value = 0;

        value = getNombre().compareTo(jugador.getNombre());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Jugador)) {
            return false;
        }

        Jugador jugador = (Jugador) obj;

        long primaryKey = jugador.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        JugadorModelImpl jugadorModelImpl = this;

        jugadorModelImpl._originalUuid = jugadorModelImpl._uuid;

        jugadorModelImpl._originalPartidoId = jugadorModelImpl._partidoId;

        jugadorModelImpl._setOriginalPartidoId = false;

        jugadorModelImpl._originalGroupId = jugadorModelImpl._groupId;

        jugadorModelImpl._setOriginalGroupId = false;

        jugadorModelImpl._originalCompanyId = jugadorModelImpl._companyId;

        jugadorModelImpl._setOriginalCompanyId = false;

        jugadorModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Jugador> toCacheModel() {
        JugadorCacheModel jugadorCacheModel = new JugadorCacheModel();

        jugadorCacheModel.uuid = getUuid();

        String uuid = jugadorCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            jugadorCacheModel.uuid = null;
        }

        jugadorCacheModel.jugadorId = getJugadorId();

        jugadorCacheModel.partidoId = getPartidoId();

        jugadorCacheModel.groupId = getGroupId();

        jugadorCacheModel.companyId = getCompanyId();

        jugadorCacheModel.userId = getUserId();

        jugadorCacheModel.userName = getUserName();

        String userName = jugadorCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            jugadorCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            jugadorCacheModel.createDate = createDate.getTime();
        } else {
            jugadorCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            jugadorCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            jugadorCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        jugadorCacheModel.nombre = getNombre();

        String nombre = jugadorCacheModel.nombre;

        if ((nombre != null) && (nombre.length() == 0)) {
            jugadorCacheModel.nombre = null;
        }

        jugadorCacheModel.dni = getDni();

        String dni = jugadorCacheModel.dni;

        if ((dni != null) && (dni.length() == 0)) {
            jugadorCacheModel.dni = null;
        }

        jugadorCacheModel.titular = getTitular();

        return jugadorCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", jugadorId=");
        sb.append(getJugadorId());
        sb.append(", partidoId=");
        sb.append(getPartidoId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", nombre=");
        sb.append(getNombre());
        sb.append(", dni=");
        sb.append(getDni());
        sb.append(", titular=");
        sb.append(getTitular());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append(
            "com.cursoliferay.liferay.portlets.alineaciones.model.Jugador");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>jugadorId</column-name><column-value><![CDATA[");
        sb.append(getJugadorId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>partidoId</column-name><column-value><![CDATA[");
        sb.append(getPartidoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nombre</column-name><column-value><![CDATA[");
        sb.append(getNombre());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>dni</column-name><column-value><![CDATA[");
        sb.append(getDni());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>titular</column-name><column-value><![CDATA[");
        sb.append(getTitular());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
