package com.cursoliferay.liferay.portlets.alineaciones.model.impl;

import com.cursoliferay.liferay.portlets.alineaciones.model.Partido;
import com.cursoliferay.liferay.portlets.alineaciones.service.PartidoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Partido service. Represents a row in the &quot;alineaciones_Partido&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PartidoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PartidoImpl
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.Partido
 * @generated
 */
public abstract class PartidoBaseImpl extends PartidoModelImpl
    implements Partido {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a partido model instance should use the {@link Partido} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PartidoLocalServiceUtil.addPartido(this);
        } else {
            PartidoLocalServiceUtil.updatePartido(this);
        }
    }
}
