package com.cursoliferay.liferay.portlets.alineaciones.model.impl;

import com.cursoliferay.liferay.portlets.alineaciones.model.Partido;
import com.cursoliferay.liferay.portlets.alineaciones.model.PartidoModel;
import com.cursoliferay.liferay.portlets.alineaciones.model.PartidoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Partido service. Represents a row in the &quot;alineaciones_Partido&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cursoliferay.liferay.portlets.alineaciones.model.PartidoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PartidoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PartidoImpl
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.Partido
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.PartidoModel
 * @generated
 */
@JSON(strict = true)
public class PartidoModelImpl extends BaseModelImpl<Partido>
    implements PartidoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a partido model instance should use the {@link com.cursoliferay.liferay.portlets.alineaciones.model.Partido} interface instead.
     */
    public static final String TABLE_NAME = "alineaciones_Partido";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "partidoId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "nombre", Types.VARCHAR },
            { "fecha", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table alineaciones_Partido (uuid_ VARCHAR(75) null,partidoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nombre VARCHAR(75) null,fecha DATE null)";
    public static final String TABLE_SQL_DROP = "drop table alineaciones_Partido";
    public static final String ORDER_BY_JPQL = " ORDER BY partido.nombre ASC";
    public static final String ORDER_BY_SQL = " ORDER BY alineaciones_Partido.nombre ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Partido"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Partido"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.cursoliferay.liferay.portlets.alineaciones.model.Partido"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UUID_COLUMN_BITMASK = 4L;
    public static long NOMBRE_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.cursoliferay.liferay.portlets.alineaciones.model.Partido"));
    private static ClassLoader _classLoader = Partido.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Partido.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _partidoId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _nombre;
    private Date _fecha;
    private long _columnBitmask;
    private Partido _escapedModel;

    public PartidoModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Partido toModel(PartidoSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Partido model = new PartidoImpl();

        model.setUuid(soapModel.getUuid());
        model.setPartidoId(soapModel.getPartidoId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setNombre(soapModel.getNombre());
        model.setFecha(soapModel.getFecha());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Partido> toModels(PartidoSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Partido> models = new ArrayList<Partido>(soapModels.length);

        for (PartidoSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _partidoId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPartidoId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _partidoId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Partido.class;
    }

    @Override
    public String getModelClassName() {
        return Partido.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("partidoId", getPartidoId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("nombre", getNombre());
        attributes.put("fecha", getFecha());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long partidoId = (Long) attributes.get("partidoId");

        if (partidoId != null) {
            setPartidoId(partidoId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String nombre = (String) attributes.get("nombre");

        if (nombre != null) {
            setNombre(nombre);
        }

        Date fecha = (Date) attributes.get("fecha");

        if (fecha != null) {
            setFecha(fecha);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getPartidoId() {
        return _partidoId;
    }

    @Override
    public void setPartidoId(long partidoId) {
        _partidoId = partidoId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getNombre() {
        if (_nombre == null) {
            return StringPool.BLANK;
        } else {
            return _nombre;
        }
    }

    @Override
    public void setNombre(String nombre) {
        _columnBitmask = -1L;

        _nombre = nombre;
    }

    @JSON
    @Override
    public Date getFecha() {
        return _fecha;
    }

    @Override
    public void setFecha(Date fecha) {
        _fecha = fecha;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Partido.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Partido.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Partido toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Partido) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PartidoImpl partidoImpl = new PartidoImpl();

        partidoImpl.setUuid(getUuid());
        partidoImpl.setPartidoId(getPartidoId());
        partidoImpl.setGroupId(getGroupId());
        partidoImpl.setCompanyId(getCompanyId());
        partidoImpl.setUserId(getUserId());
        partidoImpl.setUserName(getUserName());
        partidoImpl.setCreateDate(getCreateDate());
        partidoImpl.setModifiedDate(getModifiedDate());
        partidoImpl.setNombre(getNombre());
        partidoImpl.setFecha(getFecha());

        partidoImpl.resetOriginalValues();

        return partidoImpl;
    }

    @Override
    public int compareTo(Partido partido) {
        int value = 0;

        value = getNombre().compareTo(partido.getNombre());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Partido)) {
            return false;
        }

        Partido partido = (Partido) obj;

        long primaryKey = partido.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PartidoModelImpl partidoModelImpl = this;

        partidoModelImpl._originalUuid = partidoModelImpl._uuid;

        partidoModelImpl._originalGroupId = partidoModelImpl._groupId;

        partidoModelImpl._setOriginalGroupId = false;

        partidoModelImpl._originalCompanyId = partidoModelImpl._companyId;

        partidoModelImpl._setOriginalCompanyId = false;

        partidoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Partido> toCacheModel() {
        PartidoCacheModel partidoCacheModel = new PartidoCacheModel();

        partidoCacheModel.uuid = getUuid();

        String uuid = partidoCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            partidoCacheModel.uuid = null;
        }

        partidoCacheModel.partidoId = getPartidoId();

        partidoCacheModel.groupId = getGroupId();

        partidoCacheModel.companyId = getCompanyId();

        partidoCacheModel.userId = getUserId();

        partidoCacheModel.userName = getUserName();

        String userName = partidoCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            partidoCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            partidoCacheModel.createDate = createDate.getTime();
        } else {
            partidoCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            partidoCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            partidoCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        partidoCacheModel.nombre = getNombre();

        String nombre = partidoCacheModel.nombre;

        if ((nombre != null) && (nombre.length() == 0)) {
            partidoCacheModel.nombre = null;
        }

        Date fecha = getFecha();

        if (fecha != null) {
            partidoCacheModel.fecha = fecha.getTime();
        } else {
            partidoCacheModel.fecha = Long.MIN_VALUE;
        }

        return partidoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", partidoId=");
        sb.append(getPartidoId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", nombre=");
        sb.append(getNombre());
        sb.append(", fecha=");
        sb.append(getFecha());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append(
            "com.cursoliferay.liferay.portlets.alineaciones.model.Partido");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>partidoId</column-name><column-value><![CDATA[");
        sb.append(getPartidoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nombre</column-name><column-value><![CDATA[");
        sb.append(getNombre());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>fecha</column-name><column-value><![CDATA[");
        sb.append(getFecha());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
