package com.cursoliferay.liferay.portlets.alineaciones.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Jugador service. Represents a row in the &quot;alineaciones_Jugador&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cursoliferay.liferay.portlets.alineaciones.model.impl.JugadorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cursoliferay.liferay.portlets.alineaciones.model.impl.JugadorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Jugador
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.impl.JugadorImpl
 * @see com.cursoliferay.liferay.portlets.alineaciones.model.impl.JugadorModelImpl
 * @generated
 */
public interface JugadorModel extends BaseModel<Jugador>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a jugador model instance should use the {@link Jugador} interface instead.
     */

    /**
     * Returns the primary key of this jugador.
     *
     * @return the primary key of this jugador
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this jugador.
     *
     * @param primaryKey the primary key of this jugador
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this jugador.
     *
     * @return the uuid of this jugador
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this jugador.
     *
     * @param uuid the uuid of this jugador
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the jugador ID of this jugador.
     *
     * @return the jugador ID of this jugador
     */
    public long getJugadorId();

    /**
     * Sets the jugador ID of this jugador.
     *
     * @param jugadorId the jugador ID of this jugador
     */
    public void setJugadorId(long jugadorId);

    /**
     * Returns the partido ID of this jugador.
     *
     * @return the partido ID of this jugador
     */
    public long getPartidoId();

    /**
     * Sets the partido ID of this jugador.
     *
     * @param partidoId the partido ID of this jugador
     */
    public void setPartidoId(long partidoId);

    /**
     * Returns the group ID of this jugador.
     *
     * @return the group ID of this jugador
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this jugador.
     *
     * @param groupId the group ID of this jugador
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this jugador.
     *
     * @return the company ID of this jugador
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this jugador.
     *
     * @param companyId the company ID of this jugador
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this jugador.
     *
     * @return the user ID of this jugador
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this jugador.
     *
     * @param userId the user ID of this jugador
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this jugador.
     *
     * @return the user uuid of this jugador
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this jugador.
     *
     * @param userUuid the user uuid of this jugador
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this jugador.
     *
     * @return the user name of this jugador
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this jugador.
     *
     * @param userName the user name of this jugador
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this jugador.
     *
     * @return the create date of this jugador
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this jugador.
     *
     * @param createDate the create date of this jugador
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this jugador.
     *
     * @return the modified date of this jugador
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this jugador.
     *
     * @param modifiedDate the modified date of this jugador
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the nombre of this jugador.
     *
     * @return the nombre of this jugador
     */
    @AutoEscape
    public String getNombre();

    /**
     * Sets the nombre of this jugador.
     *
     * @param nombre the nombre of this jugador
     */
    public void setNombre(String nombre);

    /**
     * Returns the dni of this jugador.
     *
     * @return the dni of this jugador
     */
    @AutoEscape
    public String getDni();

    /**
     * Sets the dni of this jugador.
     *
     * @param dni the dni of this jugador
     */
    public void setDni(String dni);

    /**
     * Returns the titular of this jugador.
     *
     * @return the titular of this jugador
     */
    public boolean getTitular();

    /**
     * Returns <code>true</code> if this jugador is titular.
     *
     * @return <code>true</code> if this jugador is titular; <code>false</code> otherwise
     */
    public boolean isTitular();

    /**
     * Sets whether this jugador is titular.
     *
     * @param titular the titular of this jugador
     */
    public void setTitular(boolean titular);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Jugador jugador);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Jugador> toCacheModel();

    @Override
    public Jugador toEscapedModel();

    @Override
    public Jugador toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
